//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_data_source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub ip: String,
    pub port: String,
    pub database_type: String,
    pub service_id: String,
    pub database_id: String,
    pub system_code: Option<String>,
    pub system_manufacturer: String,
    pub org_code: Option<String>,
    pub org_name: Option<String>,
    pub data_source_desc: String,
    pub enable: i32,
    pub database_user: String,
    pub database_password: String,
    pub create_time: DateTime,
    pub create_user_id: String,
    pub create_user_name: String,
    pub update_time: DateTime,
    pub update_user_id: String,
    pub update_user_name: String,
    pub project_id: String,
    pub deleted: i32,
    pub data_source: String,
    pub connectable_flag: i32,
    pub connection_type: Option<String>,
    pub director_name: Option<String>,
    pub director_account: Option<String>,
    pub contactor_name: Option<String>,
    pub contactor_account: Option<String>,
    pub jdbc_url: Option<String>,
    pub common_connect: Option<i32>,
    pub jdbc_driver: Option<String>,
    pub db_attribute: Option<String>,
    pub ref_status: Option<i32>,
    pub ref_app_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
