//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_file")]
pub struct Model {
    pub file_url: Option<String>,
    pub file_type: String,
    pub file_info: String,
    pub file_size: i32,
    pub tenant_id: String,
    pub create_time: DateTime,
    pub create_user_id: String,
    pub create_user_name: String,
    pub update_time: DateTime,
    pub update_user_id: String,
    pub update_user_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub file_upload_id: String,
    pub file_path: String,
    pub file_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
