[package]
name = "hello"
version = "0.1.0"
edition = "2021"
license = "MIT"
build = "build.rs"

[[bin]]
name = "hello"
path = "src/main.rs"



[dependencies]
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"