[package]
name = "common_token"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
once_cell = { version = "1" }
dashmap="6.1.0"
jsonwebtoken = "9"
