[package]
name = "server_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
database = { path = "../database"}
extra = { path = "../extra" ,features = ["default"]}
dotenv = "0.15.0"
tokio = { version = "1", features = ["macros"] }
