app:
  name: rust-admin
  ip: 127.0.0.1
  port: 5896
  database_url: postgres://postgres:672832006myf@localhost:5432/postgres
  redis_url: redis://localhost:6379/
  jwt_secret: lr_cdr_data
  work_id: 1

nacos:
  server_addr: 127.0.0.1:8848
  config_id: rust-admin-dev.yaml
  namespace: public
  username: nacos
  password: nacos
rpc:
  name: rust-admin-rpc
  ip: 127.0.0.1
  port: 15896
global:
  ignores:
    - "/**"