//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_application")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: i32,
    pub application_group_id: String,
    pub application_source: i32,
    pub application_url: String,
    pub application_id: String,
    pub application_name: String,
    pub application_icon: String,
    pub application_desc: String,
    pub application_preview_url: String,
    pub introduction_file_name: String,
    pub application_enable: i32,
    pub application_open: i32,
    pub create_time: DateTime,
    pub create_user_id: String,
    pub create_user_name: String,
    pub update_time: DateTime,
    pub update_user_id: String,
    pub update_user_name: String,
    pub project_id: String,
    pub deleted: i32,
    pub application_icon_top: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
